### ISSUE TITLE
Why using "access_token" when the authentication method is API Token?

### ISSUE THREAD

**Issue by mfs-homero-merino** [singer-io/tap-zendesk#126]
https://github.com/singer-io/tap-zendesk/blob/2dc3cbb3425a115b4e6256313ce21ca6f20bb22a/tap_zendesk/streams.py#L151

My team is trying to use this tap with the API token authenticationn but when running ~/.virtualenv/tap-zendesk/bin/tap-zendesk --config tap-zendesk.conf --catalog catalog_zendesk.json, we're getting this error:
INFO Using API Token authentication.
INFO tickets: Starting sync
INFO Syncing ticket_audits per ticket...
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 0, "tags": {"endpoint": "tickets"}}
CRITICAL 'access_token'
Traceback (most recent call last):
  File "/home/singer/.virtualenv/tap-zendesk/bin/tap-zendesk", line 33, in <module>
    sys.exit(load_entry_point('tap-zendesk==1.7.5', 'console_scripts', 'tap-zendesk')())
  File "/home/singer/.virtualenv/tap-zendesk/lib/python3.9/site-packages/singer/utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "/home/singer/.virtualenv/tap-zendesk/lib/python3.9/site-packages/tap_zendesk/__init__.py", line 214, in main
    do_sync(client, parsed_args.catalog, state, parsed_args.config)
  File "/home/singer/.virtualenv/tap-zendesk/lib/python3.9/site-packages/tap_zendesk/__init__.py", line 144, in do_sync
    counter_value = sync_stream(state, config.get('start_date'), instance)
  File "/home/singer/.virtualenv/tap-zendesk/lib/python3.9/site-packages/tap_zendesk/sync.py", line 31, in sync_stream
    for (stream, record) in instance.sync(state):
  File "/home/singer/.virtualenv/tap-zendesk/lib/python3.9/site-packages/tap_zendesk/streams.py", line 330, in sync
    for ticket in tickets:
  File "/home/singer/.virtualenv/tap-zendesk/lib/python3.9/site-packages/tap_zendesk/streams.py", line 151, in get_objects
    for page in http.get_incremental_export(url, self.config['access_token'], self.request_timeout, start_time):
KeyError: 'access_token'

The get_objects method in CursorBasedExportStreams class uses again the config file regardless of the authentication type which causes an error in the keys. If both keys are added in config file, by default the auth method selected is Oauth. 

Any suggestion for this error? Kind regards!

**Comment by mfs-homero-merino** [comment]
![image](https://user-images.githubusercontent.com/98560926/236592061-835c5abf-7550-48cc-b703-b48eaa859ba4.png)

**Comment by mporracindie** [comment]
If using meltano you might need to include the capabilities in order to work correctly:

```yml
  - name: tap-zendesk
    namespace: tap_zendesk
    variant: blueprint-data
    pip_url: git+https://github.com/blueprint-data/tap-zendesk.git
    capabilities:
      - discover
      - catalog
      - state
```
