### ISSUE TITLE
The tap-zendesk doesn't work

### ISSUE THREAD

**Issue by melnimr** [singer-io/tap-zendesk#29]
Just simply doing:
./bin/tap-zendesk --config zendesk_config.json --catalog   catalog.json

doesn't work:

{"type": "SCHEMA", "stream": "tickets", "schema": {"properties": {"organization_id": {"type": ["null", "integer"]}, "requester_id": {"type": ["null", "integer"]}, "problem_id": {"type": ["null", "integer"]}, "is_public": {"type": ["null", "boolean"]}, "description": {"type": ["null", "string"]}, "follower_ids": {"items": {"type": ["null", "integer"]}, "type": ["null", "array"]}, "submitter_id": {"type": ["null", "integer"]}, "generated_timestamp": {"type": ["null", "integer"]}, "brand_id": {"type": ["null", "integer"]}, "id": {"type": ["null", "integer"]}, "group_id": {"type": ["null", "integer"]}, "type": {"type": ["null", "string"]}, "recipient": {"type": ["null", "string"]}, "collaborator_ids": {"items": {"type": ["null", "integer"]}, "type": ["null", "array"]}, "tags": {"items": {"type": ["null", "string"]}, "type": ["null", "array"]}, "has_incidents": {"type": ["null", "boolean"]}, "created_at": {"format": "date-time", "type": ["null", "string"]}, "raw_subject": {"type": ["null", "string"]}, "status": {"type": ["null", "string"]}, "updated_at": {"format": "date-time", "type": ["null", "string"]}, "custom_fields": {"items": {"properties": {"id": {"type": ["null", "integer"]}, "value": {}}, "type": ["null", "object"]}, "type": ["null", "array"]}, "url": {"type": ["null", "string"]}, "allow_channelback": {"type": ["null", "boolean"]}, "allow_attachments": {"type": ["null", "boolean"]}, "due_at": {"format": "date-time", "type": ["null", "string"]}, "followup_ids": {"items": {"type": ["null", "integer"]}, "type": ["null", "array"]}, "priority": {"type": ["null", "string"]}, "assignee_id": {"type": ["null", "integer"]}, "subject": {"type": ["null", "string"]}, "external_id": {"type": ["null", "string"]}, "via": {"properties": {"source": {"properties": {"from": {"properties": {"name": {"type": ["null", "string"]}, "ticket_id": {"type": ["null", "integer"]}, "address": {"type": ["null", "string"]}, "subject": {"type": ["null", "string"]}}, "type": ["null", "object"]}, "to": {"properties": {"address": {"type": ["null", "string"]}, "name": {"type": ["null", "string"]}}, "type": ["null", "object"]}, "rel": {"type": ["null", "string"]}}, "type": ["null", "object"]}, "channel": {"type": ["null", "string"]}}, "type": ["null", "object"]}, "ticket_form_id": {"type": ["null", "integer"]}, "satisfaction_rating": {"properties": {"id": {"type": ["null", "integer"]}, "assignee_id": {"type": ["null", "integer"]}, "group_id": {"type": ["null", "integer"]}, "reason_id": {"type": ["null", "integer"]}, "requester_id": {"type": ["null", "integer"]}, "ticket_id": {"type": ["null", "integer"]}, "updated_at": {"format": "date-time", "type": ["null", "string"]}, "created_at": {"format": "date-time", "type": ["null", "string"]}, "url": {"type": ["null", "string"]}, "score": {"type": ["null", "string"]}, "reason": {"type": ["null", "string"]}, "comment": {"type": ["null", "string"]}}, "type": ["null", "object", "string"]}, "sharing_agreement_ids": {"items": {"type": ["null", "integer"]}, "type": ["null", "array"]}, "email_cc_ids": {"items": {"type": ["null", "integer"]}, "type": ["null", "array"]}, "forum_topic_id": {"type": ["null", "integer"]}}, "type": ["null", "object"]}, "key_properties": ["id"]}
sub_stream_names ['ticket_audits']
sub_stream_name :  ticket_audits
1 {'tickets': <class 'tap_zendesk.streams.Tickets'>, 'groups': <class 'tap_zendesk.streams.Groups'>, 'users': <class 'tap_zendesk.streams.Users'>, 'organizations': <class 'tap_zendesk.streams.Organizations'>, 'ticket_audits': <class 'tap_zendesk.streams.TicketAudits'>, 'ticket_comments': <class 'tap_zendesk.streams.TicketComments'>, 'ticket_fields': <class 'tap_zendesk.streams.TicketFields'>, 'ticket_forms': <class 'tap_zendesk.streams.TicketForms'>, 'group_memberships': <class 'tap_zendesk.streams.GroupMemberships'>, 'macros': <class 'tap_zendesk.streams.Macros'>, 'satisfaction_ratings': <class 'tap_zendesk.streams.SatisfactionRatings'>, 'tags': <class 'tap_zendesk.streams.Tags'>, 'ticket_metrics': <class 'tap_zendesk.streams.TicketMetrics'>, 'sla_policies': <class 'tap_zendesk.streams.SLAPolicies'>}
2 None
CRITICAL 'NoneType' object has no attribute 'metadata'
Traceback (most recent call last):
  File "./bin/tap-zendesk", line 11, in <module>
    load_entry_point('tap-zendesk==1.4.6', 'console_scripts', 'tap-zendesk')()
  File "/Users/neo/wellth-wrk/singer-io/singer-target/env/lib/python3.7/site-packages/singer_python-5.2.1-py3.7.egg/singer/utils.py", line 192, in wrapped
    return fnc(*args, **kwargs)
  File "/Users/neo/wellth-wrk/singer-io/singer-target/env/lib/python3.7/site-packages/tap_zendesk-1.4.6-py3.7.egg/tap_zendesk/__init__.py", line 205, in main
    do_sync(client, parsed_args.catalog, state, parsed_args.config['start_date'])
  File "/Users/neo/wellth-wrk/singer-io/singer-target/env/lib/python3.7/site-packages/tap_zendesk-1.4.6-py3.7.egg/tap_zendesk/__init__.py", line 133, in do_sync
    sub_mdata = metadata.to_map(sub_stream.metadata)
AttributeError: 'NoneType' object has no attribute 'metadata'

**Comment by hz-lschick** [comment]
@melnimr I guess this is already solved, it works for me
