### ISSUE TITLE
Error satisfaction ratings stream when paired with Postgres Target

### ISSUE THREAD

**Issue by j-oflaherty** [singer-io/tap-zendesk#55]
Hi, 
I've run into a problem when selecting the satisfaction ratings stream alongside the postgres target. Here is the error:
```
Traceback (most recent call last):
  File ".virtualenvs/target-postgres/bin/target-postgres", line 8, in <module>
    sys.exit(cli())
  File "/[working_dir]/.virtualenvs/target-postgres/lib/python3.8/site-packages/target_postgres/__init__.py", line 45, in cli
    main(args.config)
  File "/[working_dir]/.virtualenvs/target-postgres/lib/python3.8/site-packages/target_postgres/__init__.py", line 39, in main
    target_tools.main(postgres_target)
  File "/[working_dir]/.virtualenvs/target-postgres/lib/python3.8/site-packages/target_postgres/target_tools.py", line 28, in main
    stream_to_target(input_stream, target, config=config)
  File "/[working_dir]/.virtualenvs/target-postgres/lib/python3.8/site-packages/target_postgres/target_tools.py", line 77, in stream_to_target
    raise e
  File "/[working_dir]/.virtualenvs/target-postgres/lib/python3.8/site-packages/target_postgres/target_tools.py", line 58, in stream_to_target
    _line_handler(state_tracker,
  File "/[working_dir]/.virtualenvs/target-postgres/lib/python3.8/site-packages/target_postgres/target_tools.py", line 123, in _line_handler
    buffered_stream = BufferedSingerStream(stream,
  File "/[working_dir]/.virtualenvs/target-postgres/lib/python3.8/site-packages/target_postgres/singer_stream.py", line 47, in __init__
    self.update_schema(schema, key_properties)
  File "/[working_dir]/.virtualenvs/target-postgres/lib/python3.8/site-packages/target_postgres/singer_stream.py", line 75, in update_schema
    properties = self.schema['properties']
KeyError: 'properties'
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.5887002944946289, "tags": {"status": "succeeded"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 1, "tags": {"endpoint": "satisfaction_ratings"}}
CRITICAL [Errno 32] Broken pipe
Traceback (most recent call last):
  File ".virtualenvs/tap-zendesk/bin/tap-zendesk", line 11, in <module>
    load_entry_point('tap-zendesk', 'console_scripts', 'tap-zendesk')()
  File "/[working_dir]/.virtualenvs/tap-zendesk/lib/python3.8/site-packages/singer/utils.py", line 192, in wrapped
    return fnc(*args, **kwargs)
  File "/[working_dir]/zendesk-tap/tap_zendesk/__init__.py", line 200, in main
    do_sync(client, parsed_args.catalog, state, parsed_args.config)
  File "/[working_dir]/zendesk-tap/tap_zendesk/__init__.py", line 137, in do_sync
    counter_value = sync_stream(state, config.get('start_date'), instance)
  File "/[working_dir]/zendesk-tap/tap_zendesk/sync.py", line 40, in sync_stream
    singer.write_record(stream.tap_stream_id, rec)
  File "/[working_dir]/.virtualenvs/tap-zendesk/lib/python3.8/site-packages/singer/messages.py", line 226, in write_record
    write_message(RecordMessage(stream=(stream_alias or stream_name),
  File "/[working_dir]/.virtualenvs/tap-zendesk/lib/python3.8/site-packages/singer/messages.py", line 218, in write_message
    sys.stdout.flush()
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

When running it by itself or with a csv target it works fine. I've also tried it with the google sheets target and the same error occurs. 

 OS: Ubuntu 20.04.1 LTS,
        Codename: Focal

**Comment by dmosorast** [comment]
@j-oflaherty From the looks of the stack trace, this is an issue with target-postgres. When the target process exits with a `KeyError`, the tap process exits with a broken pipe.

I believe `target-postgres` is maintained by a Singer community member at this repo: https://github.com/datamill-co/target-postgres
